### ISSUE TITLE
Recursive rendering?

### ISSUE THREAD

**Issue by myriadtim** [kolypto/j2cli#69]
If I have a foo.yaml:

```
---
vendors:
   - A
   - B
   - C
questions:
   - Q1: {{ vendor }} foo
   - Q2: {{ vendor }} foo
```

and a foo.j2:

```
{% for vendor in vendors %}
{% for q in questions %}
{{ q }}
{% endfor %}
{% endfor %}

```

Is it possible to get j2cli to parse "vendor" as part of the for loop for q, almost as if I was doing a recursive or nested template?
